# Generated by Django 2.2.1 on 2020-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btlship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsusers',
            name='user2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
