# Generated by Django 2.2.1 on 2020-05-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btlship', '0002_auto_20200505_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('channel_name', models.CharField(max_length=30)),
            ],
        ),
    ]
