# Generated by Django 2.2.1 on 2020-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btlship', '0004_requesttogame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsusers',
            name='user2',
            field=models.CharField(max_length=30),
        ),
    ]
