# Generated by Django 2.2.1 on 2020-06-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btlship', '0005_auto_20200514_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('userFirst', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='idGame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='btlship.Games'),
        ),
    ]
